export const SCREENS = {
  HOME: 'Home',
  REGISTER: 'Register',
  OTP_VERIFICATION: 'OTPVerification',
  EMAIL_INPUT: 'EmailInput',
  EMAIL_OTP_VERIFICATION: 'EmailOTPVerification',
  PASSWORD: 'Password',
  REGISTRATION_SUCCESS: 'RegistrationSuccess',
  PURCHASE: 'Purchase',
  PAYMENT_SELECTION: 'PaymentSelection',
  PAYMENT_METHOD_DETAIL: 'PaymentMethodDetail',
  MOBILE_PAYMENT: 'MobilePayment',
  MOVEMENTS: 'Movements',
  TEST: 'Test',
  PROFILE: 'Profile',
  SEARCH: 'Search',
  NOTIFICATION: 'Notification',
  NOTIFICATIONS: 'Notifications',
  DETAIL: 'Detail',
  ONBOARDING: 'Onboarding',
  SPLASH: 'Splash',
  LOGIN: 'Login',
  SELLER: {
    HOME: 'SellerHome',
    REGISTER: 'SellerRegister',
  },
  CONTRACTS: 'Contracts',
};
