// ? Screens
export const SCREENS = {
  ONBOARDING: 'Onboarding',
  LOGIN: 'CreditivooLogin',
  REGISTER: 'Register',
  HOME: 'Home',
  OTP_VERIFICATION: 'OTPVerification',
  SUCCESSFUL_REGISTRATION: 'Successful Registration',
  PAYMENT_SELECTION: 'Payment Selection',
  MOBILE_PAYMENT: 'Mobile Payment', //TODO: MOBILE_PAYMENT must be a branch from PAYMENT_SELECTION
  MOVEMENTS: 'Movements',
  PAYMENT_METHOD_DETAIL: 'Payment Method Detail',
  PAYMENT_METHOD_SELECTION: 'Payment Method Selection',
  PURCHASES: 'Purchases',
  TEST: 'Test',
  PROFILE: 'Perfil',
  STORES: 'Stores',
  BRANCH_DETAIL: 'Branch Detail',
  PERSONAL_INFORMATION: 'Personal Information',
  FAQ: 'FAQ',
  CONTACT_SUPPORT: 'Contact Support',
  SEARCH: 'Search',
  NOTIFICATIONS: 'Notification',
  DETAIL: 'Detail',
  SELLER_AUTH: 'Seller auth',
  SELLER_SIGNUP: 'Seller sign up',
  FORGOT_PASSWORD: 'Forgot password',
  DEVICE_INFO: 'Device Info',
  CONTRACTS: 'Contracts',
  DEVICE_CONFIG: 'Device Config',
  PURCHASE_DETAIL: 'Purchase Detail',
  SPLASH: 'Splash',
};
