export default {
  sora: {
    bold: 'Sora-Bold',
    extraBold: 'Sora-ExtraBold',
    extraLight: 'Sora-ExtraLight',
    italic: 'Sora-Italic',
    light: 'Sora-Light',
    lightItalic: 'Sora-LightItalic',
    medium: 'Sora-Medium',
    regular: 'Sora-Regular',
    semiBold: 'Sora-SemiBold',
    thin: 'Sora-Thin',
  },
  poppins: {
    black: 'Poppins-Black',
    blackItalic: 'Poppins-BlackItalic',
    bold: 'Poppins-Bold',
    boldItalic: 'Poppins-BoldItalic',
    extraBold: 'Poppins-ExtraBold',
    extraBoldItalic: 'Poppins-ExtraBoldItalic',
    extraLight: 'Poppins-ExtraLight',
    extraLightItalic: 'Poppins-ExtraLightItalic',
    italic: 'Poppins-Italic',
    light: 'Poppins-Light',
    lightItalic: 'Poppins-LightItalic',
    medium: 'Poppins-Medium',
    mediumItalic: 'Poppins-MediumItalic',
    regular: 'Poppins-Regular',
    semiBold: 'Poppins-SemiBold',
    semiBoldItalic: 'Poppins-SemiBoldItalic',
    thin: 'Poppins-Thin',
    thinItalic: 'Poppins-ThinItalic',
  },
  raleway: {
    black: 'Raleway-Black',
    blackItalic: 'Raleway-BlackItalic',
    bold: 'Raleway-Bold',
    boldItalic: 'Raleway-BoldItalic',
    extraBold: 'Raleway-ExtraBold',
    extraBoldItalic: 'Raleway-ExtraBoldItalic',
    extraLight: 'Raleway-ExtraLight',
    extraLightItalic: 'Raleway-ExtraLightItalic',
    italic: 'Raleway-Italic',
    light: 'Raleway-Light',
    lightItalic: 'Raleway-LightItalic',
    medium: 'Raleway-Medium',
    mediumItalic: 'Raleway-MediumItalic',
    regular: 'Raleway-Regular',
    semiBold: 'Raleway-SemiBold',
    semiBoldItalic: 'Raleway-SemiBoldItalic',
    thin: 'Raleway-Thin',
    thinItalic: 'Raleway-ThinItalic',
  },
  urbanist: {
    regular: 'Urbanist-Regular',
    semiBold: 'Urbanist-SemiBold',
    bold: 'Urbanist-Bold',
  },
};
