export default {
  ic_gmail: require('../../assets/images/gmail.png'),
  ic_fb: require('../../assets/images/social/Facebook.png'),
  ic_apple: require('../../assets/images/social/Apple.png'),
  ic_appleB: require('../../assets/images/social/AppleB.png'),
  ic_arrow: require('../../assets/images/arrow.png'),
  ic_email: require('../../assets/images/email.png'),
  ic_wishlist: require('../../assets/images/wishlist.png'),
  ic_wishlist_active: require('../../assets/images/ic_wishlist_active.png'),
  ic_arrow_down: require('../../assets/images/ic_arrow_down.png'),
  ic_arrow_up: require('../../assets/images/ic_arrow_up.png'),
  ic_arrow_down_white: require('../../assets/images/ic_arrow_down_white.png'),
  ic_arrow_up_white: require('../../assets/images/ic_arrow_up_white.png'),
  ic_Plus: require('../../assets/images/Plus.png'),
  ic_plus_gray: require('../../assets/images/plus_gray.png'),
  ic_account_success: require('../../assets/images/account_success.png'),
  ic_user_singup: require('../../assets/images/ic_user_singup.png'),
  ic_checked_green: require('../../assets/images/checked_green.png'),
  ic_mapview: require('../../assets/images/mapview.png'),
  ic_mapview_new: require('../../assets/images/mapview_new.png'),
  ic_listview: require('../../assets/images/listview.png'),
  ic_listview_new: require('../../assets/images/listview_new.png'),
  ic_store: require('../../assets/images/store.png'),
  ic_store_new: require('../../assets/images/store_new.png'),
  ic_share: require('../../assets/images/ic_share.png'),
  ic_share_new: require('../../assets/images/ic_share_new.png'),
  ic_wishlist_detail_de: require('../../assets/images/ic_wishlist_detail.png'),
  ic_wishlist_detail_new: require('../../assets/images/ic_wishlist_detail_new.png'),
  ic_wishlist_detail_se: require('../../assets/images/ic_wishlist_detail_se.png'),
  ic_mappin_inactive: require('../../assets/images/pin_inactive.png'),
  ic_mappin_active: require('../../assets/images/pin_active.png'),

  // Rout.js File
  ic_home_green: require('../../assets/images/tab/ic_home_green.png'),
  ic_home_gray: require('../../assets/images/tab/ic_home_gray.png'),
  ic_home_dark: require('../../assets/images/tab/ic_home_dark.png'),
  ic_home_white: require('../../assets/images/tab/ic_home_white.png'),

  ic_search_green: require('../../assets/images/tab/ic_search_green.png'),
  ic_search_dark: require('../../assets/images/tab/ic_search_dark.png'),
  ic_search: require('../../assets/images/tab/ic_search.png'),
  ic_search_white: require('../../assets/images/tab/ic_search_white.png'),
  
  ic_creditivo: require('../../assets/images/tab/asset_105.png'),
  ic_creditivodark: require('../../assets/images/tab/25px-white-stroke.png'),
  ic_creditivodark_b: require('../../assets/images/tab/49px-white-stroke.png'),
  ic_creditivodark_c: require('../../assets/images/tab/72px-logo.png'),
  ic_creditivodark_green: require('../../assets/images/tab/creditivoo24px.png'),
  ic_creditivodark_green_a: require('../../assets/images/tab/creditivoo48px.png'),
  ic_creditivodark_green_b: require('../../assets/images/tab/creditivoo72px.png'),
  ic_creditivo_green: require('../../assets/images/tab/25px-green-stroke.png'),
  ic_creditivo_green_b: require('../../assets/images/tab/49px-green-stroke.png'),
  ic_creditivo_green_c: require('../../assets/images/tab/73px-green-stroke.png'),
  // ic_creditivo_b: require('../../assets/images/tab/creditivoo-48px.png'),
  // ic_creditivo_c: require('../../assets/images/tab/creditivoo-72px.png'),

  ic_cart_dark: require('../../assets/images/tab/ic_cart_dark.png'),
  ic_cart_green: require('../../assets/images/tab/ic_cart_green.png'),
  ic_cart: require('../../assets/images/tab/ic_cart.png'),
  ic_cart_white: require('../../assets/images/tab/ic_cart_white.png'),

  ic_wishlist_green: require('../../assets/images/tab/ic_wishlist_green.png'),
  ic_wishlist_dark: require('../../assets/images/tab/ic_wishlist_dark.png'),
  ic_wishlist_t: require('../../assets/images/tab/ic_wishlist.png'),
  ic_wishlist_white: require('../../assets/images/tab/ic_wishlist_white_new.png'),

  ic_profile_green: require('../../assets/images/tab/ic_profile_green.png'),
  ic_profile_dark: require('../../assets/images/tab/ic_profile_dark.png'),
  ic_profile: require('../../assets/images/tab/ic_profile.png'),
  ic_profile_bottom_white: require('../../assets/images/tab/ic_profile_white_new.png'),
  ic_profile_black: require('../../assets/images/ic_profile_black.png'),

  //User Profile Page
  ic_order_history: require('../../assets/images/profile/ic_profile_order_history.png'),
  ic_order_history_dark: require('../../assets/images/profile/ic_profile_order_history_dark.png'),
  ic_order_product: require('../../assets/images/profile/ic_profile_order_product.png'),
  ic_order_product_dark: require('../../assets/images/profile/ic_profile_order_product_dark.png'),
  ic_profile_fav: require('../../assets/images/profile/ic_profile_fav.png'),
  ic_profile_address: require('../../assets/images/profile/ic_profile_address.png'),
  ic_profile_address_dark: require('../../assets/images/profile/ic_profile_address_dark.png'),
  ic_profile_cc: require('../../assets/images/profile/ic_profile_cc.png'),
  ic_profile_cc_dark: require('../../assets/images/profile/ic_profile_cc_dark.png'),
  ic_profile_changepassword: require('../../assets/images/profile/ic_profile_changepassword.png'),
  ic_profile_changepassword_dark: require('../../assets/images/profile/ic_profile_changepassword_dark.png'),
  ic_profile_contactform: require('../../assets/images/profile/ic_profile_contactform.png'),
  ic_profile_contactform_dark: require('../../assets/images/profile/ic_profile_contactform_dark.png'),
  ic_profile_bug: require('../../assets/images/profile/ic_profile_bug.png'),
  ic_profile_logout: require('../../assets/images/profile/ic_profile_logout.png'),
  ic_delete_account: require('../../assets/images/profile/delete-accout.png'),
  ic_delete_account_light: require('../../assets/images/profile/ic_delete_accout.png'),
  ic_delete_account_dark: require('../../assets/images/profile/ic_delete_accout_dark.png'),
  ic_profile_permision: require('../../assets/images/profile/shield.png'),
  ic_profile_permision_dark: require('../../assets/images/profile/shield_dark.png'),
  ic_notification: require('../../assets/images/profile/ic_notification.png'),
  ic_notification_setting: require('../../assets/images/profile/ic_notification_setting.png'),
  ic_notification_setting_dark: require('../../assets/images/profile/ic_notification_setting_dark.png'),
  ic_theme_light: require('../../assets/images/profile/ic_dark.png'),
  ic_theme_dark: require('../../assets/images/profile/ic_dark_dark.png'),
  ic_chat: require('../../assets/images/profile/ic_account_chat.png'),
  ic_chat_dark: require('../../assets/images/profile/ic_account_chat_dark.png'),


  vd_splash_celebration: require('../../assets/video/splash.mp4'),
  vd_splash: require('../../assets/video/splash1.mp4'),
  vd_splash_new: require('../../assets/video/splash33.mp4'),
  vd_splash_android: require('../../assets/video/spash_android.mp4'),
  vd_splash_screen_ios: require('../../assets/video/vd_ios.mp4'),
  vd_splash_screen_android: require('../../assets/video/vd_android_.mp4'),

  ic_add_home_de: require('../../assets/images/address/ic_add_home_de.png'),
  ic_add_home_de_new: require('../../assets/images/address/ic_add_home_de_new.png'),
  ic_add_home_de_selected: require('../../assets/images/address/ic_add_home_green.png'),
  ic_add_work: require('../../assets/images/address/ic_add_work.png'),
  ic_add_work_new: require('../../assets/images/address/ic_add_work_new.png'),
  ic_add_work_selected: require('../../assets/images/address/ic_add_work_green.png'),
  ic_add_other: require('../../assets/images/address/ic_add_other.png'),
  ic_add_other_new: require('../../assets/images/address/ic_add_other_new.png'),
  ic_add_other_selected: require('../../assets/images/address/ic_add_other_green.png'),
  ic_close_modal: require('../../assets/images/close.png'),
  ic_checkout_notification: require('../../assets/images/notification.png'),
  ic_checkout_bag: require('../../assets/images/bag.png'),
  img_cancelledOrder: require('../../assets/images/img_canceledorder.png'),
  img_Notification: require('../../assets/images/PNotification.png'),
  Check: require('../../assets/images/Check.png'),
  ic_close: require('../../assets/images/ic_close.png'),
  video_bg: require('../../assets/images/video_bg.png'),

  // Launch Screen Images

  ic_S1: require('../../assets/images/Intro/ES_1.png'),
  ic_S2: require('../../assets/images/Intro/ES_2.png'),
  ic_S3: require('../../assets/images/Intro/ES_3.png'),
  ic_S4: require('../../assets/images/Intro/ES_4.png'),
  ic_S5: require('../../assets/images/Intro/ES_5.png'),
  ic_S6: require('../../assets/images/Intro/ES_6.png'),

  ic_Cash: require('../../assets/images/Cash.png'),
  ic_Card: require('../../assets/images/Card.png'),
  ic_visa: require('../../assets/images/ic_visa.png'),
  ic_mastercard: require('../../assets/images/ic_mastercard.png'),
  ic_movil: require('../../assets/images/ic_movil.png'),
  ic_zelle: require('../../assets/images/ic_zelle.png'),
  ic_boli: require('../../assets/images/ic_boli.png'),
  ic_paypal: require('../../assets/images/ic_paypal.png'),
  ic_banesco: require('../../assets/images/Iconos_Banesco.png'),

  ic_pen: require('../../assets/images/Pen.png'),
  ic_Store_active: require('../../assets/images/Store_active.png'),

  ic_close_red: require('../../assets/images/close_red.png'),
  ic_Filters: require('../../assets/images/Filters.png'),
  ic_Filters_white: require('../../assets/images/Filters_white.png'),
  ic_Filters_black: require('../../assets/images/Filters_black.png'),
  ic_Filters_Active: require('../../assets/images/Active.png'),
  ic_Slider: require('../../assets/images/Slider.png'),
  ic_filtrar: require('../../assets/images/ic_filtrar.png'),
  ic_Home: require('../../assets/images/Home.png'),
  ic_Home_Green_Theme: require('../../assets/images/HomeGreen.png'),
  ic_Home_Green_Theme2: require('../../assets/images/HomeGreen2.png'),
  ic_home_logo_white_theme: require('../../assets/images/home_green_white_theme.png'),
  ic_home_logo_black_theme: require('../../assets/images/home_green_black_theme.png'),
  ic_buttonplus: require('../../assets/images/ic_buttonplus.png'),
  ic_exal: require('../../assets/images/ic_exal.png'),
  ic_amex: require('../../assets/images/ic_amex.png'),

  ic_light: require('../../assets/images/light.png'),
  ic_dark: require('../../assets/images/dark.png'),
  ic_notification_bell: require('../../assets/images/ic_notification_bell.png'),
  ic_bell: require('../../assets/images/ic_bell_ring.png'),
  ivoo: require('../../assets/images/ivoo.png'),

  ic_info: require('../../assets/images/ic_info_new.png'),
};
